// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Fodro/saberchan/internal/ban (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_store.go -package=mocks github.com/Fodro/saberchan/internal/ban Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	ban "github.com/Fodro/saberchan/internal/ban"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetBan mocks base method.
func (m *MockStore) GetBan(ctx context.Context, key string) (*ban.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBan", ctx, key)
	ret0, _ := ret[0].(*ban.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBan indicates an expected call of GetBan.
func (mr *MockStoreMockRecorder) GetBan(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBan", reflect.TypeOf((*MockStore)(nil).GetBan), ctx, key)
}

// SetBan mocks base method.
func (m *MockStore) SetBan(ctx context.Context, key string, record ban.Record, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBan", ctx, key, record, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBan indicates an expected call of SetBan.
func (mr *MockStoreMockRecorder) SetBan(ctx, key, record, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBan", reflect.TypeOf((*MockStore)(nil).SetBan), ctx, key, record, ttl)
}
