services:
  frontend:
    build: 
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      MAIN_BACKEND_URL: http://backend:8888
      PORT: 8080

  backend:
    build: 
      context: backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8888