services:
  frontend:
    build: 
      dockerfile: frontend.Dockerfile
    ports:
      - "5127:80"
    environment:
      MAIN_BACKEND_URL: http://backend:8888
      OIDC_REALM: ${OIDC_REALM}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      AUTH_HOST: ${AUTH_HOST}

  backend:
    build: 
      dockerfile: backend.Dockerfile
    ports:
      - "8888:8888"
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SSL_MODE: ${SSL_MODE}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

    