services:
  frontend:
    build:
      context: frontend
      dockerfile: ../frontend.Dockerfile
      args:
        MAIN_BACKEND_URL: http://backend:8888
        OIDC_REALM: ${OIDC_REALM}
        OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
        OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
        AUTH_HOST: ${AUTH_HOST}
        AUTH_SECRET: ${AUTH_SECRET}
        OIDC_REDIRECT_URI: ${OIDC_REDIRECT_URI}
        OIDC_LOGOUT_REDIRECT_URI: ${OIDC_LOGOUT_REDIRECT_URI}
    ports:
      - "3000:3000"

  backend:
    build:
      context: backend
      dockerfile: ../backend.Dockerfile
    ports:
      - "8888:8888"
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SSL_MODE: ${SSL_MODE}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - 9090:8080