services:
  backend:
    build: 
      context: backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
  
  frontend:
    build: 
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "5127"
    environment:
      MAIN_BACKEND_URL: http://backend:8888
      PORT: 5127

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend