// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Fodro/saberchan/internal/database (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/database/mocks/mock_repository.go -package=mocks github.com/Fodro/saberchan/internal/database Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	database "github.com/Fodro/saberchan/internal/database"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddAttachment mocks base method.
func (m *MockRepository) AddAttachment(ctx context.Context, attachment *database.Attachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAttachment", ctx, attachment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAttachment indicates an expected call of AddAttachment.
func (mr *MockRepositoryMockRecorder) AddAttachment(ctx, attachment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAttachment", reflect.TypeOf((*MockRepository)(nil).AddAttachment), ctx, attachment)
}

// AddBoard mocks base method.
func (m *MockRepository) AddBoard(ctx context.Context, board *database.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBoard", ctx, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBoard indicates an expected call of AddBoard.
func (mr *MockRepositoryMockRecorder) AddBoard(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBoard", reflect.TypeOf((*MockRepository)(nil).AddBoard), ctx, board)
}

// AddConfig mocks base method.
func (m *MockRepository) AddConfig(ctx context.Context, config *database.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddConfig indicates an expected call of AddConfig.
func (mr *MockRepositoryMockRecorder) AddConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConfig", reflect.TypeOf((*MockRepository)(nil).AddConfig), ctx, config)
}

// AddPost mocks base method.
func (m *MockRepository) AddPost(ctx context.Context, post *database.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPost", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPost indicates an expected call of AddPost.
func (mr *MockRepositoryMockRecorder) AddPost(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPost", reflect.TypeOf((*MockRepository)(nil).AddPost), ctx, post)
}

// AddThread mocks base method.
func (m *MockRepository) AddThread(ctx context.Context, thread *database.Thread) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddThread", ctx, thread)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddThread indicates an expected call of AddThread.
func (mr *MockRepositoryMockRecorder) AddThread(ctx, thread any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddThread", reflect.TypeOf((*MockRepository)(nil).AddThread), ctx, thread)
}

// BumpThread mocks base method.
func (m *MockRepository) BumpThread(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpThread", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpThread indicates an expected call of BumpThread.
func (mr *MockRepositoryMockRecorder) BumpThread(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpThread", reflect.TypeOf((*MockRepository)(nil).BumpThread), ctx, id)
}

// ChangeCurrConfig mocks base method.
func (m *MockRepository) ChangeCurrConfig(ctx context.Context, configId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeCurrConfig", ctx, configId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeCurrConfig indicates an expected call of ChangeCurrConfig.
func (mr *MockRepositoryMockRecorder) ChangeCurrConfig(ctx, configId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeCurrConfig", reflect.TypeOf((*MockRepository)(nil).ChangeCurrConfig), ctx, configId)
}

// CheckIfThreadBelowBumpLimit mocks base method.
func (m *MockRepository) CheckIfThreadBelowBumpLimit(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfThreadBelowBumpLimit", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfThreadBelowBumpLimit indicates an expected call of CheckIfThreadBelowBumpLimit.
func (mr *MockRepositoryMockRecorder) CheckIfThreadBelowBumpLimit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfThreadBelowBumpLimit", reflect.TypeOf((*MockRepository)(nil).CheckIfThreadBelowBumpLimit), ctx, id)
}

// CountThreads mocks base method.
func (m *MockRepository) CountThreads(ctx context.Context, boardID uuid.UUID, includeDeleted bool) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountThreads", ctx, boardID, includeDeleted)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountThreads indicates an expected call of CountThreads.
func (mr *MockRepositoryMockRecorder) CountThreads(ctx, boardID, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountThreads", reflect.TypeOf((*MockRepository)(nil).CountThreads), ctx, boardID, includeDeleted)
}

// DeleteAttachmentsByPostID mocks base method.
func (m *MockRepository) DeleteAttachmentsByPostID(ctx context.Context, postID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachmentsByPostID", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachmentsByPostID indicates an expected call of DeleteAttachmentsByPostID.
func (mr *MockRepositoryMockRecorder) DeleteAttachmentsByPostID(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachmentsByPostID", reflect.TypeOf((*MockRepository)(nil).DeleteAttachmentsByPostID), ctx, postID)
}

// DeleteBoard mocks base method.
func (m *MockRepository) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBoard", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBoard indicates an expected call of DeleteBoard.
func (mr *MockRepositoryMockRecorder) DeleteBoard(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBoard", reflect.TypeOf((*MockRepository)(nil).DeleteBoard), ctx, id)
}

// DeletePost mocks base method.
func (m *MockRepository) DeletePost(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockRepositoryMockRecorder) DeletePost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockRepository)(nil).DeletePost), ctx, id)
}

// DeleteThread mocks base method.
func (m *MockRepository) DeleteThread(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteThread", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteThread indicates an expected call of DeleteThread.
func (mr *MockRepositoryMockRecorder) DeleteThread(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteThread", reflect.TypeOf((*MockRepository)(nil).DeleteThread), ctx, id)
}

// GetAttachments mocks base method.
func (m *MockRepository) GetAttachments(ctx context.Context, postID uuid.UUID) ([]database.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachments", ctx, postID)
	ret0, _ := ret[0].([]database.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachments indicates an expected call of GetAttachments.
func (mr *MockRepositoryMockRecorder) GetAttachments(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachments", reflect.TypeOf((*MockRepository)(nil).GetAttachments), ctx, postID)
}

// GetAttachmentsByPostIDs mocks base method.
func (m *MockRepository) GetAttachmentsByPostIDs(ctx context.Context, postIDs []uuid.UUID) ([]database.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentsByPostIDs", ctx, postIDs)
	ret0, _ := ret[0].([]database.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentsByPostIDs indicates an expected call of GetAttachmentsByPostIDs.
func (mr *MockRepositoryMockRecorder) GetAttachmentsByPostIDs(ctx, postIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentsByPostIDs", reflect.TypeOf((*MockRepository)(nil).GetAttachmentsByPostIDs), ctx, postIDs)
}

// GetBoardByAlias mocks base method.
func (m *MockRepository) GetBoardByAlias(ctx context.Context, alias string, includeDeleted bool) (*database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoardByAlias", ctx, alias, includeDeleted)
	ret0, _ := ret[0].(*database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoardByAlias indicates an expected call of GetBoardByAlias.
func (mr *MockRepositoryMockRecorder) GetBoardByAlias(ctx, alias, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoardByAlias", reflect.TypeOf((*MockRepository)(nil).GetBoardByAlias), ctx, alias, includeDeleted)
}

// GetBoardById mocks base method.
func (m *MockRepository) GetBoardById(ctx context.Context, id uuid.UUID, includeDeleted bool) (*database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoardById", ctx, id, includeDeleted)
	ret0, _ := ret[0].(*database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoardById indicates an expected call of GetBoardById.
func (mr *MockRepositoryMockRecorder) GetBoardById(ctx, id, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoardById", reflect.TypeOf((*MockRepository)(nil).GetBoardById), ctx, id, includeDeleted)
}

// GetBoardCatalog mocks base method.
func (m *MockRepository) GetBoardCatalog(ctx context.Context, boardID uuid.UUID, limit, offset int, includeDeleted bool) ([]database.CatalogThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoardCatalog", ctx, boardID, limit, offset, includeDeleted)
	ret0, _ := ret[0].([]database.CatalogThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoardCatalog indicates an expected call of GetBoardCatalog.
func (mr *MockRepositoryMockRecorder) GetBoardCatalog(ctx, boardID, limit, offset, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoardCatalog", reflect.TypeOf((*MockRepository)(nil).GetBoardCatalog), ctx, boardID, limit, offset, includeDeleted)
}

// GetBoards mocks base method.
func (m *MockRepository) GetBoards(ctx context.Context, includeDeleted bool) ([]database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoards", ctx, includeDeleted)
	ret0, _ := ret[0].([]database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoards indicates an expected call of GetBoards.
func (mr *MockRepositoryMockRecorder) GetBoards(ctx, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoards", reflect.TypeOf((*MockRepository)(nil).GetBoards), ctx, includeDeleted)
}

// GetConfigs mocks base method.
func (m *MockRepository) GetConfigs(ctx context.Context) ([]database.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigs", ctx)
	ret0, _ := ret[0].([]database.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigs indicates an expected call of GetConfigs.
func (mr *MockRepositoryMockRecorder) GetConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigs", reflect.TypeOf((*MockRepository)(nil).GetConfigs), ctx)
}

// GetCurrentConfig mocks base method.
func (m *MockRepository) GetCurrentConfig(ctx context.Context) (*database.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentConfig", ctx)
	ret0, _ := ret[0].(*database.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentConfig indicates an expected call of GetCurrentConfig.
func (mr *MockRepositoryMockRecorder) GetCurrentConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentConfig", reflect.TypeOf((*MockRepository)(nil).GetCurrentConfig), ctx)
}

// GetFollowThreadInfos mocks base method.
func (m *MockRepository) GetFollowThreadInfos(ctx context.Context, ids []uuid.UUID) ([]database.FollowThreadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowThreadInfos", ctx, ids)
	ret0, _ := ret[0].([]database.FollowThreadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowThreadInfos indicates an expected call of GetFollowThreadInfos.
func (mr *MockRepositoryMockRecorder) GetFollowThreadInfos(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowThreadInfos", reflect.TypeOf((*MockRepository)(nil).GetFollowThreadInfos), ctx, ids)
}

// GetOPPost mocks base method.
func (m *MockRepository) GetOPPost(ctx context.Context, threadID uuid.UUID) (*database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOPPost", ctx, threadID)
	ret0, _ := ret[0].(*database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOPPost indicates an expected call of GetOPPost.
func (mr *MockRepositoryMockRecorder) GetOPPost(ctx, threadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOPPost", reflect.TypeOf((*MockRepository)(nil).GetOPPost), ctx, threadID)
}

// GetPost mocks base method.
func (m *MockRepository) GetPost(ctx context.Context, id uuid.UUID) (*database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, id)
	ret0, _ := ret[0].(*database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockRepositoryMockRecorder) GetPost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockRepository)(nil).GetPost), ctx, id)
}

// GetPosts mocks base method.
func (m *MockRepository) GetPosts(ctx context.Context, threadID uuid.UUID, includeDeleted bool) ([]database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx, threadID, includeDeleted)
	ret0, _ := ret[0].([]database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockRepositoryMockRecorder) GetPosts(ctx, threadID, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockRepository)(nil).GetPosts), ctx, threadID, includeDeleted)
}

// GetRepliesForThread mocks base method.
func (m *MockRepository) GetRepliesForThread(ctx context.Context, threadID uuid.UUID, includeDeleted bool) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepliesForThread", ctx, threadID, includeDeleted)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepliesForThread indicates an expected call of GetRepliesForThread.
func (mr *MockRepositoryMockRecorder) GetRepliesForThread(ctx, threadID, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepliesForThread", reflect.TypeOf((*MockRepository)(nil).GetRepliesForThread), ctx, threadID, includeDeleted)
}

// GetThread mocks base method.
func (m *MockRepository) GetThread(ctx context.Context, id uuid.UUID, includeDeleted bool) (*database.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThread", ctx, id, includeDeleted)
	ret0, _ := ret[0].(*database.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThread indicates an expected call of GetThread.
func (mr *MockRepositoryMockRecorder) GetThread(ctx, id, includeDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThread", reflect.TypeOf((*MockRepository)(nil).GetThread), ctx, id, includeDeleted)
}

// GetThreads mocks base method.
func (m *MockRepository) GetThreads(ctx context.Context, boardID uuid.UUID) ([]database.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreads", ctx, boardID)
	ret0, _ := ret[0].([]database.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreads indicates an expected call of GetThreads.
func (mr *MockRepositoryMockRecorder) GetThreads(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreads", reflect.TypeOf((*MockRepository)(nil).GetThreads), ctx, boardID)
}

// InTx mocks base method.
func (m *MockRepository) InTx(ctx context.Context, fn func(database.Repository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTx indicates an expected call of InTx.
func (mr *MockRepositoryMockRecorder) InTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTx", reflect.TypeOf((*MockRepository)(nil).InTx), ctx, fn)
}

// ListBoardsDueForPurge mocks base method.
func (m *MockRepository) ListBoardsDueForPurge(ctx context.Context, before time.Time) ([]database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBoardsDueForPurge", ctx, before)
	ret0, _ := ret[0].([]database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBoardsDueForPurge indicates an expected call of ListBoardsDueForPurge.
func (mr *MockRepositoryMockRecorder) ListBoardsDueForPurge(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBoardsDueForPurge", reflect.TypeOf((*MockRepository)(nil).ListBoardsDueForPurge), ctx, before)
}

// ListPostsDueForPurge mocks base method.
func (m *MockRepository) ListPostsDueForPurge(ctx context.Context, before time.Time) ([]database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostsDueForPurge", ctx, before)
	ret0, _ := ret[0].([]database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostsDueForPurge indicates an expected call of ListPostsDueForPurge.
func (mr *MockRepositoryMockRecorder) ListPostsDueForPurge(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostsDueForPurge", reflect.TypeOf((*MockRepository)(nil).ListPostsDueForPurge), ctx, before)
}

// ListThreadsDueForPurge mocks base method.
func (m *MockRepository) ListThreadsDueForPurge(ctx context.Context, before time.Time) ([]database.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListThreadsDueForPurge", ctx, before)
	ret0, _ := ret[0].([]database.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThreadsDueForPurge indicates an expected call of ListThreadsDueForPurge.
func (mr *MockRepositoryMockRecorder) ListThreadsDueForPurge(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThreadsDueForPurge", reflect.TypeOf((*MockRepository)(nil).ListThreadsDueForPurge), ctx, before)
}

// MarkBoardPurged mocks base method.
func (m *MockRepository) MarkBoardPurged(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBoardPurged", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBoardPurged indicates an expected call of MarkBoardPurged.
func (mr *MockRepositoryMockRecorder) MarkBoardPurged(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBoardPurged", reflect.TypeOf((*MockRepository)(nil).MarkBoardPurged), ctx, id)
}

// MarkPostPurged mocks base method.
func (m *MockRepository) MarkPostPurged(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPostPurged", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPostPurged indicates an expected call of MarkPostPurged.
func (mr *MockRepositoryMockRecorder) MarkPostPurged(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPostPurged", reflect.TypeOf((*MockRepository)(nil).MarkPostPurged), ctx, id)
}

// MarkThreadPurged mocks base method.
func (m *MockRepository) MarkThreadPurged(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkThreadPurged", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkThreadPurged indicates an expected call of MarkThreadPurged.
func (mr *MockRepositoryMockRecorder) MarkThreadPurged(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkThreadPurged", reflect.TypeOf((*MockRepository)(nil).MarkThreadPurged), ctx, id)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}

// RestoreBoard mocks base method.
func (m *MockRepository) RestoreBoard(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreBoard", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreBoard indicates an expected call of RestoreBoard.
func (mr *MockRepositoryMockRecorder) RestoreBoard(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreBoard", reflect.TypeOf((*MockRepository)(nil).RestoreBoard), ctx, id)
}

// RestorePost mocks base method.
func (m *MockRepository) RestorePost(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestorePost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestorePost indicates an expected call of RestorePost.
func (mr *MockRepositoryMockRecorder) RestorePost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestorePost", reflect.TypeOf((*MockRepository)(nil).RestorePost), ctx, id)
}

// RestoreThread mocks base method.
func (m *MockRepository) RestoreThread(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreThread", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreThread indicates an expected call of RestoreThread.
func (mr *MockRepositoryMockRecorder) RestoreThread(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreThread", reflect.TypeOf((*MockRepository)(nil).RestoreThread), ctx, id)
}

// SoftDeleteBoard mocks base method.
func (m *MockRepository) SoftDeleteBoard(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteBoard", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteBoard indicates an expected call of SoftDeleteBoard.
func (mr *MockRepositoryMockRecorder) SoftDeleteBoard(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteBoard", reflect.TypeOf((*MockRepository)(nil).SoftDeleteBoard), ctx, id)
}

// SoftDeletePost mocks base method.
func (m *MockRepository) SoftDeletePost(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeletePost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeletePost indicates an expected call of SoftDeletePost.
func (mr *MockRepositoryMockRecorder) SoftDeletePost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeletePost", reflect.TypeOf((*MockRepository)(nil).SoftDeletePost), ctx, id)
}

// SoftDeleteThread mocks base method.
func (m *MockRepository) SoftDeleteThread(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteThread", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteThread indicates an expected call of SoftDeleteThread.
func (mr *MockRepositoryMockRecorder) SoftDeleteThread(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteThread", reflect.TypeOf((*MockRepository)(nil).SoftDeleteThread), ctx, id)
}

// UpdateBoard mocks base method.
func (m *MockRepository) UpdateBoard(ctx context.Context, board *database.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBoard", ctx, board)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBoard indicates an expected call of UpdateBoard.
func (mr *MockRepositoryMockRecorder) UpdateBoard(ctx, board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBoard", reflect.TypeOf((*MockRepository)(nil).UpdateBoard), ctx, board)
}
