// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Fodro/saberchan/internal/database (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks github.com/Fodro/saberchan/internal/database Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	database "github.com/Fodro/saberchan/internal/database"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddAttachment mocks base method.
func (m *MockRepository) AddAttachment(attachment *database.Attachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAttachment", attachment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAttachment indicates an expected call of AddAttachment.
func (mr *MockRepositoryMockRecorder) AddAttachment(attachment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAttachment", reflect.TypeOf((*MockRepository)(nil).AddAttachment), attachment)
}

// AddBoard mocks base method.
func (m *MockRepository) AddBoard(board *database.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBoard", board)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBoard indicates an expected call of AddBoard.
func (mr *MockRepositoryMockRecorder) AddBoard(board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBoard", reflect.TypeOf((*MockRepository)(nil).AddBoard), board)
}

// AddConfig mocks base method.
func (m *MockRepository) AddConfig(config *database.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConfig", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddConfig indicates an expected call of AddConfig.
func (mr *MockRepositoryMockRecorder) AddConfig(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConfig", reflect.TypeOf((*MockRepository)(nil).AddConfig), config)
}

// AddPost mocks base method.
func (m *MockRepository) AddPost(post *database.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPost", post)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPost indicates an expected call of AddPost.
func (mr *MockRepositoryMockRecorder) AddPost(post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPost", reflect.TypeOf((*MockRepository)(nil).AddPost), post)
}

// AddThread mocks base method.
func (m *MockRepository) AddThread(thread *database.Thread) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddThread", thread)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddThread indicates an expected call of AddThread.
func (mr *MockRepositoryMockRecorder) AddThread(thread any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddThread", reflect.TypeOf((*MockRepository)(nil).AddThread), thread)
}

// BumpThread mocks base method.
func (m *MockRepository) BumpThread(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpThread", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpThread indicates an expected call of BumpThread.
func (mr *MockRepositoryMockRecorder) BumpThread(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpThread", reflect.TypeOf((*MockRepository)(nil).BumpThread), id)
}

// ChangeCurrConfig mocks base method.
func (m *MockRepository) ChangeCurrConfig(configId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeCurrConfig", configId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeCurrConfig indicates an expected call of ChangeCurrConfig.
func (mr *MockRepositoryMockRecorder) ChangeCurrConfig(configId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeCurrConfig", reflect.TypeOf((*MockRepository)(nil).ChangeCurrConfig), configId)
}

// CheckIfThreadBelowBumpLimit mocks base method.
func (m *MockRepository) CheckIfThreadBelowBumpLimit(id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfThreadBelowBumpLimit", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfThreadBelowBumpLimit indicates an expected call of CheckIfThreadBelowBumpLimit.
func (mr *MockRepositoryMockRecorder) CheckIfThreadBelowBumpLimit(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfThreadBelowBumpLimit", reflect.TypeOf((*MockRepository)(nil).CheckIfThreadBelowBumpLimit), id)
}

// DeleteBoard mocks base method.
func (m *MockRepository) DeleteBoard(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBoard", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBoard indicates an expected call of DeleteBoard.
func (mr *MockRepositoryMockRecorder) DeleteBoard(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBoard", reflect.TypeOf((*MockRepository)(nil).DeleteBoard), id)
}

// DeletePost mocks base method.
func (m *MockRepository) DeletePost(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockRepositoryMockRecorder) DeletePost(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockRepository)(nil).DeletePost), id)
}

// DeleteThread mocks base method.
func (m *MockRepository) DeleteThread(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteThread", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteThread indicates an expected call of DeleteThread.
func (mr *MockRepositoryMockRecorder) DeleteThread(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteThread", reflect.TypeOf((*MockRepository)(nil).DeleteThread), id)
}

// GetAttachments mocks base method.
func (m *MockRepository) GetAttachments(postID uuid.UUID) ([]database.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachments", postID)
	ret0, _ := ret[0].([]database.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachments indicates an expected call of GetAttachments.
func (mr *MockRepositoryMockRecorder) GetAttachments(postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachments", reflect.TypeOf((*MockRepository)(nil).GetAttachments), postID)
}

// GetBoardByAlias mocks base method.
func (m *MockRepository) GetBoardByAlias(alias string) (*database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoardByAlias", alias)
	ret0, _ := ret[0].(*database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoardByAlias indicates an expected call of GetBoardByAlias.
func (mr *MockRepositoryMockRecorder) GetBoardByAlias(alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoardByAlias", reflect.TypeOf((*MockRepository)(nil).GetBoardByAlias), alias)
}

// GetBoardById mocks base method.
func (m *MockRepository) GetBoardById(id uuid.UUID) (*database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoardById", id)
	ret0, _ := ret[0].(*database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoardById indicates an expected call of GetBoardById.
func (mr *MockRepositoryMockRecorder) GetBoardById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoardById", reflect.TypeOf((*MockRepository)(nil).GetBoardById), id)
}

// GetBoards mocks base method.
func (m *MockRepository) GetBoards() ([]database.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoards")
	ret0, _ := ret[0].([]database.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoards indicates an expected call of GetBoards.
func (mr *MockRepositoryMockRecorder) GetBoards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoards", reflect.TypeOf((*MockRepository)(nil).GetBoards))
}

// GetConfigs mocks base method.
func (m *MockRepository) GetConfigs() ([]database.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigs")
	ret0, _ := ret[0].([]database.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigs indicates an expected call of GetConfigs.
func (mr *MockRepositoryMockRecorder) GetConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigs", reflect.TypeOf((*MockRepository)(nil).GetConfigs))
}

// GetCurrentConfig mocks base method.
func (m *MockRepository) GetCurrentConfig() (*database.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentConfig")
	ret0, _ := ret[0].(*database.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentConfig indicates an expected call of GetCurrentConfig.
func (mr *MockRepositoryMockRecorder) GetCurrentConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentConfig", reflect.TypeOf((*MockRepository)(nil).GetCurrentConfig))
}

// GetOPPost mocks base method.
func (m *MockRepository) GetOPPost(threadID uuid.UUID) (*database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOPPost", threadID)
	ret0, _ := ret[0].(*database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOPPost indicates an expected call of GetOPPost.
func (mr *MockRepositoryMockRecorder) GetOPPost(threadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOPPost", reflect.TypeOf((*MockRepository)(nil).GetOPPost), threadID)
}

// GetPost mocks base method.
func (m *MockRepository) GetPost(id uuid.UUID) (*database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", id)
	ret0, _ := ret[0].(*database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockRepositoryMockRecorder) GetPost(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockRepository)(nil).GetPost), id)
}

// GetPosts mocks base method.
func (m *MockRepository) GetPosts(threadID uuid.UUID) ([]database.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", threadID)
	ret0, _ := ret[0].([]database.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockRepositoryMockRecorder) GetPosts(threadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockRepository)(nil).GetPosts), threadID)
}

// GetRepliesForThread mocks base method.
func (m *MockRepository) GetRepliesForThread(threadID uuid.UUID) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepliesForThread", threadID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepliesForThread indicates an expected call of GetRepliesForThread.
func (mr *MockRepositoryMockRecorder) GetRepliesForThread(threadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepliesForThread", reflect.TypeOf((*MockRepository)(nil).GetRepliesForThread), threadID)
}

// GetThread mocks base method.
func (m *MockRepository) GetThread(id uuid.UUID) (*database.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThread", id)
	ret0, _ := ret[0].(*database.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThread indicates an expected call of GetThread.
func (mr *MockRepositoryMockRecorder) GetThread(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThread", reflect.TypeOf((*MockRepository)(nil).GetThread), id)
}

// GetThreads mocks base method.
func (m *MockRepository) GetThreads(boardID uuid.UUID) ([]database.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreads", boardID)
	ret0, _ := ret[0].([]database.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreads indicates an expected call of GetThreads.
func (mr *MockRepositoryMockRecorder) GetThreads(boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreads", reflect.TypeOf((*MockRepository)(nil).GetThreads), boardID)
}

// Ping mocks base method.
func (m *MockRepository) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping))
}

// UpdateBoard mocks base method.
func (m *MockRepository) UpdateBoard(board *database.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBoard", board)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBoard indicates an expected call of UpdateBoard.
func (mr *MockRepositoryMockRecorder) UpdateBoard(board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBoard", reflect.TypeOf((*MockRepository)(nil).UpdateBoard), board)
}
